name: Bug Report
description: Create a report to help us improve Gemini Bridge
title: "[BUG] "
labels: ["bug", "triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 
        
        Before submitting, please search existing issues to avoid duplicates.

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: Please provide detailed steps to reproduce the issue.
      placeholder: |
        1. Run command '...'
        2. Call MCP tool with '...'
        3. See error
      value: |
        1. 
        2. 
        3. 
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe what you expected to happen...
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened instead?
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: textarea
    id: error-output
    attributes:
      label: Error Output
      description: If applicable, paste any error messages or stack traces.
      placeholder: Paste error output here...
      render: shell

  - type: dropdown
    id: environment-os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - macOS
        - Ubuntu Linux
        - Windows
        - Other Linux
        - Other (specify in additional context)
    validations:
      required: true

  - type: input
    id: environment-python
    attributes:
      label: Python Version
      description: What version of Python are you using?
      placeholder: "e.g., 3.11.5"
    validations:
      required: true

  - type: input
    id: environment-gemini-bridge
    attributes:
      label: Gemini Bridge Version
      description: What version of Gemini Bridge are you using?
      placeholder: "e.g., 1.0.0"
    validations:
      required: true

  - type: input
    id: environment-gemini-cli
    attributes:
      label: Gemini CLI Version
      description: What version of Gemini CLI do you have installed?
      placeholder: "Run: gemini --version"
    validations:
      required: true

  - type: dropdown
    id: installation-method
    attributes:
      label: Installation Method
      description: How did you install Gemini Bridge?
      options:
        - uvx (recommended)
        - pip install -e .
        - Other (specify in additional context)
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: |
        Add any other context about the problem here.
        - Screenshots
        - Configuration details
        - Related issues
      placeholder: Any additional context...

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm you have done the following
      options:
        - label: I have searched for existing issues
          required: true
        - label: I can reproduce this bug consistently
          required: true
        - label: I am using a supported Python version (3.9+)
          required: true
        - label: Gemini CLI is installed and authenticated
          required: true